apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: A sample service to demonstrate Harness IDP catalog
  tags:
    - java
    - backend
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: example-system
